# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    build_ios_app

    firebase_app_distribution(
            app: "myweatherapp-cbeca",
            testers: "mungaimrtn@gmail.com",
            release_notes: "Lots of amazing new features to test out!"
        )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
